gap_follow:
  ros__parameters:
    control_rate_hz:  50.0
    estop_min_dist:   0.5    # [m]
    estop_angle_deg: 30.0    # [deg]
    gf_bubble_radius: 0.3    # [m]
    gf_speed:         2.0    # [m/s]
    gf_max_steer:     0.4    # [rad]
    gf_max_range:    10.0    # [m]

wall_follow:
  ros__parameters:
    control_rate_hz:  50.0
    estop_min_dist:   0.5    # [m]
    estop_angle_deg: 30.0    # [deg]
    wf_target_dist:   0.7    # desired gap from right wall [m]   0.7
    wf_kp:            1.0
    wf_ki:            0.0
    wf_kd:            0.1
    wf_speed:         4.0    # [m/s]    1.5
    wf_max_steer:     0.4    # [rad]
    wf_lookahead:     0.5    # [m]
